# Generated by Django 6.0.6 on 2026-06-27 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientInventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_changed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('ADJUSTMENT', 'Adjustment'), ('WASTAGE', 'Wastage')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ingredients.ingredient')),
            ],
        ),
    ]
