# Generated by Django 6.0.6 on 2026-06-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredientinventorylog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientInventoryLog',
            new_name='IngredientStockLog',
        ),
    ]
