# Generated by Django 6.0.6 on 2026-09-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_rename_ingredientinventorylog_ingredientstocklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientstocklog',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('ADJUSTMENT', 'Adjustment'), ('WASTAGE', 'Wastage'), ('RETURN', 'Return')], max_length=20),
        ),
    ]
