# Generated by Django 6.0.6 on 2026-06-27 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_transaction_payment_method_payment'),
        ('ingredients', '0003_rename_ingredientinventorylog_ingredientstocklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.ingredient')),
                ('transaction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_used', to='billing.transactionitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('transaction_item', 'ingredient'), name='unique_transaction_item_ingredient')],
            },
        ),
    ]
