# Generated by Django 6.0.6 on 2026-06-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_transactionitemingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=20),
        ),
    ]
