# Generated by Django 6.0.6 on 2026-08-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_transaction_status'),
        ('products', '0008_productcategory_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('DIRECT', 'Direct'), ('PRODUCT', 'Product')], max_length=20)),
                ('value_type', models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], max_length=20, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('buy_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('free_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product')),
            ],
        ),
    ]
