# Generated by Django 6.0.6 on 2026-08-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_transaction_direct_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='combo_overrides',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='ingredient_overrides',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
