# Generated by Django 6.0.6 on 2026-08-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_transactionitem_combo_overrides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='inventory_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
