# Generated by Django 6.0.6 on 2026-08-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
