# Generated by Django 6.0.6 on 2026-08-17 07:42

import uuid

from django.db import migrations, models


def fix_duplicate_invoice_tokens(apps, schema_editor):
    Transaction = apps.get_model("billing", "Transaction")

    seen_tokens = set()

    transactions = (
        Transaction.objects
        .all()
        .order_by("id")
    )

    for transaction in transactions:

        token = transaction.invoice_token

        if token is None:
            transaction.invoice_token = uuid.uuid4()
            transaction.save(
                update_fields=["invoice_token"]
            )
            continue

        token_string = str(token)

        if token_string in seen_tokens:
            new_token = uuid.uuid4()

            while str(new_token) in seen_tokens:
                new_token = uuid.uuid4()

            transaction.invoice_token = new_token

            transaction.save(
                update_fields=["invoice_token"]
            )

            seen_tokens.add(str(new_token))

        else:
            seen_tokens.add(token_string)


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0012_transaction_invoice_token"),
    ]

    operations = [
        migrations.RunPython(
            fix_duplicate_invoice_tokens,
            migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name="transaction",
            name="invoice_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
    ]