# Generated by Django 6.0.6 on 2026-08-17 07:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_transaction_invoice_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
