# Generated by Django 6.0.6 on 2026-06-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='quantity_changed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='transaction_type',
            field=models.CharField(choices=[('STOCK_IN', 'Stock In'), ('SALE', 'Sale')], default='SALE', max_length=20),
        ),
    ]
