# Generated by Django 6.0.6 on 2026-09-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorylog_quantity_changed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='added_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='transaction_type',
            field=models.CharField(choices=[('STOCK_IN', 'Stock In'), ('SALE', 'Sale'), ('WASTAGE', 'Wastage')], default='SALE', max_length=20),
        ),
    ]
