# Generated by Django 6.0.6 on 2026-06-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('gst_number', models.CharField(blank=True, max_length=50)),
                ('footer_message', models.CharField(default='Thank You Visit Again', max_length=255)),
            ],
        ),
    ]
