# Generated by Django 6.0.6 on 2026-06-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logo/'),
        ),
    ]
