# Generated by Django 6.0.6 on 2026-06-27 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_rename_ingredientinventorylog_ingredientstocklog'),
        ('products', '0003_recipeingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredientAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='allow_substitution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('product', 'ingredient'), name='unique_recipe_ingredient'),
        ),
        migrations.AddField(
            model_name='recipeingredientalternative',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
        ),
        migrations.AddField(
            model_name='recipeingredientalternative',
            name='recipe_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='products.recipeingredient'),
        ),
    ]
