# Generated by Django 6.0.6 on 2026-06-27 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_recipeingredientalternative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('COMBO', 'Combo')], default='PRODUCT', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('combo', models.ForeignKey(limit_choices_to={'product_type': 'COMBO'}, on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='products.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_combos', to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('combo', 'product'), name='unique_combo_product')],
            },
        ),
    ]
