# Generated by Django 6.0.6 on 2026-07-07 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboItemAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='products.comboitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('combo_item', 'product')},
            },
        ),
    ]
